#!/usr/bin/env bash

check_systemd_hook()
{
    declare -F add_systemd_unit > /dev/null 2>&1
    if [[ ! $? -eq 0 ]]; then
        echo "systemd hook is not enabled; exit"
        return 1
    fi
}

add_ask_password_agent ()
{
    cat << EOF > "${BUILDROOT}/root/.profile"
systemd-tty-ask-password-agent --query
EOF
}

build ()
{
    check_systemd_hook || return 0
    add_ask_password_agent
}

help ()
{
    cat << EOF
This hook adds the command `systemd-tty-ask-password-agent --query` to
`/root/.profile` (for `sh` invocation).
EOF
}
